// To construct this constant, load the openEO API spec's `openapi.json` doc as `api` in a JS environment and run the following code:
// '[\n' + Object.keys(api.paths).map(p => Object.keys(api.paths[p]).filter(m => m != 'parameters').map(m => "    '" + m.toUpperCase() + ' ' + p + "'").join(",\n")).join(",\n") + '\n]'
// In the long run, we might publish the API spec to NPM. Then it could be specified as a dependency and so this constant could be derived dynamically.
export const OPENEO_V0_3_1_ENDPOINTS = [
    'GET /',
    'GET /output_formats',
    'GET /collections',
    'GET /collections/{name}',
    'GET /processes',
    'GET /credentials/oidc',
    'GET /credentials/basic',
    'POST /validation',
    'POST /preview',
    'GET /process_graphs',
    'POST /process_graphs',
    'GET /process_graphs/{process_graph_id}',
    'PATCH /process_graphs/{process_graph_id}',
    'DELETE /process_graphs/{process_graph_id}',
    'GET /service_types',
    'GET /services',
    'POST /services',
    'PATCH /services/{service_id}',
    'GET /services/{service_id}',
    'DELETE /services/{service_id}',
    'GET /jobs',
    'POST /jobs',
    'PATCH /jobs/{job_id}',
    'GET /jobs/{job_id}',
    'DELETE /jobs/{job_id}',
    'GET /jobs/{job_id}/estimate',
    'GET /jobs/{job_id}/results',
    'POST /jobs/{job_id}/results',
    'DELETE /jobs/{job_id}/results',
    'GET /files/{user_id}',
    'GET /files/{user_id}/{path}',
    'PUT /files/{user_id}/{path}',
    'DELETE /files/{user_id}/{path}',
    'GET /me',
    'GET /subscription'
];
